apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: argo-workflows-controller
    context: argo/workflows
    sync:
      infer:
      - '**/*'
deploy:
  kubectl:
    manifests:
    - ./k8s/deployment.yaml
    - ./k8s/service.yaml