apiVersion: skaffold/v3beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: argo-workflows-controller
    context: argo/workflows
    sync:
      infer:
      - '**/*'
deploy:
  kubectl:
    manifests:
    - ./k8s/*