apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: default
data:
  config: |
    {
      "artifactRepository": {
        "s3": {
          "bucket": "my-bucket",
          "keyPrefix": "my-prefix",
          "endpoint": "s3.amazonaws.com",
          "insecure": false,
          "accessKeySecret": {
            "name": "my-s3-credentials",
            "key": "accessKey"
          },
          "secretKeySecret": {
            "name": "my-s3-credentials",
            "key": "secretKey"
          }
        }
      }
    }