apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-workflows-controller
  labels:
    app: argo-workflows-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-workflows-controller
  template:
    metadata:
      labels:
        app: argo-workflows-controller
    spec:
      containers:
      - name: argo-workflows-controller
        image: argo-workflows-controller:latest
        ports:
        - containerPort: 8080
        env:
        - name: LEADER_ELECTION_IDENTITY
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
            ephemeral-storage: 1Gi
          requests:
            cpu: 100m
            memory: 64Mi
            ephemeral-storage: 512Mi
        securityContext:
          capabilities:
            add: ["SYS_RESOURCE"]
          runAsUser: 0
