apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: argo-workflows-controller
    context: ./shared/skaffold/argo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./shared/skaffold/argo/argo-workflows-controller.yaml
